_wandb:
    value:
        cli_version: 0.24.0
        code_path: code/HFDRL_UNIT8/ppo.py
        e:
            zww6vq7hi1gznoirx5iv0j66abp9f154:
                args:
                    - --track
                    - --cuda
                codePath: HFDRL_UNIT8/ppo.py
                codePathLocal: ppo.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "982240026624"
                        used: "257333288960"
                email: brennan.drake47903@gmail.com
                executable: /home/brennan/Desktop/HuggingFace_DRL_Course/HFDRL_UNIT8/.venv/bin/python3
                git:
                    commit: e72ae08853b7e944a32e00a3a8d7c7b6ee013e8c
                    remote: https://github.com/BrennanDrake/HuggingFace_DRL_Course.git
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-7e2d147d-895d-2114-2672-ed01eaf9eac1
                host: brennan-dev
                memory:
                    total: "33555038208"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/brennan/Desktop/HuggingFace_DRL_Course/HFDRL_UNIT8/ppo.py
                python: CPython 3.10.19
                root: /home/brennan/Desktop/HuggingFace_DRL_Course/HFDRL_UNIT8
                startedAt: "2026-01-16T06:52:56.732124Z"
                writerId: zww6vq7hi1gznoirx5iv0j66abp9f154
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.10.19
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
cuda:
    value: true
exp_name:
    value: ppo
gym_id:
    value: LunarLander-v3
learning_rate:
    value: 0.00025
seed:
    value: 1
torch_deterministic:
    value: true
total_timesteps:
    value: 25000
track:
    value: true
wandb_entity:
    value: null
wandb_project_name:
    value: cleanRL
